---
name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup the build env
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            podman \
            qemu-user-static\
            pkg-config \
            libdbus-1-dev && \
          cargo binstall --no-confirm cross

      - name: Build for x86_64 linux gnu
        run: |
          cargo build --release
          cp target/release/bluetui bluetui-x86_64-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            [Release.md](${{ github.server_url }}/${{ github.repository }}/blob/master/Release.md)
          files: "bluetui*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
